//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace websilabo
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitud
    {
        public int idSolicitud1 { get; set; }
        public string asunto1 { get; set; }
        public string estado1 { get; set; }
        public string codigoRemitente1 { get; set; }
        public string nombreDoc1 { get; set; }
        public string documento1 { get; set; }
        public string FechaRegistro1 { get; set; }
        public string TipoSolicitud1 { get; set; }
        public string AreaDestino1 { get; set; }
        public Nullable<int> idUsuario1 { get; set; }
    
        public virtual tusuario tusuario { get; set; }
    }
}
